version: '3.1'

services:

  grpc-server-amd64:
    build:
      context: ../../
      dockerfile: docker/amd64/Dockerfile
    image: grpc-server-amd64
    ports:
      - "8082:8082"
    expose:
      - "8082"
    container_name: grpc-server-amd64